# still in beta
# os:
#   - linux
#   - osx
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
  - jruby-head
notifications:
  slack:
    secure: KCr8I8N78I0wOX5Cx8nJwPMM7jEDEPHI9z2RCIaANLy+sdFkV3Jz1RAx/6F4hctVzHHDWirZ7lWjRwljuBtV31rTSga1YRInxXvreWyLorN6stZAC4ZGZG4SMqUZCeAmgKp2WdweYeRAHLOy2fW9jLeoBOFtyl8PkooHmob7isA=
addons:
  code_climate:
    repo_token: e470e0610710700b03b559ceb7cbe2972d02735cc687a4dd6c2dac6f86fc4950
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install sox
script: bundle exec rake travis_spec
